# Generated by Django 4.1.13 on 2024-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0002_interest_fasttext_vector_interest_scibert_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
