# Generated by Django 4.1.13 on 2024-05-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom', '0003_remove_customuser_interests_customuser_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests_fasttext_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests_scibert_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
